const moment = require('moment-timezone');
const axios = require('axios');

module.exports.config = {
 name: 'autosend',
 version: '10.02',
 hasPermission: 3,
 credits: 'DongDev',
 description: 'Tự động gửi tin nhắn theo giờ đã cài!',
 commandCategory: 'Admin',
 usages: '[]',
 cooldowns: 3,
 images: [],
};

const weather = require('weather-js');
const findWeather = (city, degreeType = 'C') => {
 return new Promise((resolve, reject) => {
 weather.find({ search: city, degreeType }, (err, result) => {
 if (err) {
 reject(err);
 } else {
 resolve(result);
 }
 });
 });
};
const thinh = ["Gọi chị là đồ ăn\nVì không có chị thì em sẽ gầy",
    "Gọi chị là thời trang yodi\nBởi vì chị lookgood feelgood",
    "Em ví dụ mình như số 4-6\nĐể được ở cùng quanh 5",
    "Gọi chị là Cô Giáo\nBởi vì cứ gặp chị là em muốn Trả Bài",
    "Gọi chị là cái ghế\nVì em yêu chị khỏi phải Bàn",
    "Gọi em là thẩm phán\nVì thấy em là anh muốn chung thân",
    "Một nụ cười bằng 10 thang thuốc bổ\nVì vậy anh muốn cả ngày smile (sờ mai)",
    "Anh cực ghét ngày mùng 1-6\nBởi vì ngày đó là ngày Thiếu Nhi",
    "Em là một hoạ sĩ tồi\nVì em vẽ cầu vồng thì thiếu nắng, vẽ hạnh phúc thì thiếu anh",
    "Muốn một lần đưa Roma sang Luân Đôn\nĐể em thấy được thành ý trong anh",
    "Pascal thì viết phương trình\nCòn anh thì viết chuyện tình hai ta",
    "Cu, CuCl2 và Fe3o4 thì có thể kết tủa\nCòn anh và em thì có thể kết hôn",
    "Nhìn em anh lại nhớ đến Ngô Tất Tố\nBởi vì anh chỉ muốn tắt đèn",
    "Trái tim anh đang dao động điều hoà\nTừ khi em đến bỗng lệch pha",
    "Nhìn em anh thấy yêu động vật\nVì chỉ có em làm anh thích thú",
    "Anh chỉ muốn chúng mình là heo\nĐể được cùng em ăn và ngủ",
    "Anh biết em thích badboy\nAnh đây trai tốt nào đâu có phần\nVì tính anh không vui nhưng mà túi anh không vơi",
     "Gọi em là Nội 1972\nVì khiến anh ngày đêm không ngủ",
    "Gặp em anh chỉ muốn nhìn sang trái\nĐể thấy yêu em là phải",
    "Gọi em là đèn đỏ\nVì thấy em là anh biết điểm dừng",
    "Nắng kia đâu làm anh cháy\nNhưng em cười chắc chắn làm anh say",
    "Gọi em là ngã rẽ\nVì gặp em là anh phải cua",
    "Trông cậu hài quá\nToi cuoi cau duoc khong?",
    "Gọi em là Cách Mạng Tháng 8\n Vì em là Thời cơ ngàn năm có một",
    "Em có thể nhờ anh tất cả\nKể cả nhờ ơ nhơ sắc nhớ",
    "Vì em ngọt ngào\nNên tim anh mới lọt vào",
    "Ngắm hoàng hôn anh quên cả trời tối\nNgắm em cười anh quên cả thanh xuân",
    "Xuân Diệu thì biết làm thơ\nCòn anh chỉ biết ngẩn ngơ nhìn nàng",
    "Nếu em coi tình yêu là giọt nước biển\nAnh sẽ đổ cả đại dương vào tim em",
    "Gặp em anh bỗng nặng đầu\nTrên đầu là tóc, trong đầu là em",
    "Gọi em là sunlight\nVì thấy em là anh muốn chén sạch",
    "Em là khói, anh là thịt heo\nTại vì thịt heo sẽ được hun khói",
    "Anh muốn làm cảnh sát giao thông\nĐể dắt em vào le duong",
    "Tính cả rồi\nNhưng gặp em lại rối cả tình",
    "Gọi anh là Florentino còn em là hoa\nVì anh không thể để hụt mất em",
    "Bầu trời nhiêu mây lại thiếu nắng\nLòng ta trống vắng vì thiếu em",
    "Tặng em 1 quả chanh thần\nCắt ra là sự chân thành",
    "Gọi em là Canada 1867\nVì em đã từng thuộc về Anh",
    "Thời tiết này yêu anh là hợp lý\nEm mà bỏ phí thì là em ngu",
    "Mùa đông gió lạnh từng cơn\nYêu anh thì sẽ thích hơn một mình",
    "Đài báo hôm nay trời trở gió\nEm đi đâu đó nhớ mang theo anh",
    "Em ơi nắng ấm xa dần\nĐông sang gió lạnh anh cần em thôi",
    "Mỗi ngày anh trả cho em một chiếc thơm\nĐó gọi là thuế má",
    "Yêu em như x trong phương trình\nBiết rằng vô nghiệm vẫn yêu em",
    "Nguyễn Du lúc viết Truyện Kiều\nHình như viết thiếu là Kiều thua em",
    "Anh học rất dốt văn\nBởi vì yêu em tới khó tả",
    "Covid thì anh không dính\nNhưng yêu em thì anh dương tính",
    "Gọi em là nam châm\nAnh là từ trường vì lúc nào anh cũng tồn tại quanh em",
    "Nghe nói em có nụ cười toả nắng\nVay em thu cuoi anh xem",
    "Gọi em là Hong Kong 1841\nVì khi đó em thuộc về Anh",
    "Gọi em là cà phê\nVì càng cà càng phê",
    "Em có thể cười một chút không\nVì cà phê anh quên bỏ đường rồi",
    "Thiếu oxi ta không thể thở\nVẻ đẹp của nàng thơ không thể tả",
    "Tách ly dùng để uống trà\nTình ca để hát, em là để yêu.",
    "Anh cho phép em ở mãi trong trái tim anh đấy.",
      "Cái gì đầy trong mắt em đó? Hình như là anh.",
      "Số trời đã định,\nkhông phải lòng em,\nchắc chắn anh sẽ ế.",
      "Nhà em có bán rượu không mà sao nói chuyện với em làm anh cứ chếnh choáng?",
      "Có rất nhiều cách để hạnh phúc.\nNhanh nhất chính là nhìn thấy em.",
      "Hãy để một lần cho anh được yêu em.",
      "Hôm nay 14 tháng 3,\nmà sao chưa ai tặng quà anh nhỉ?.",
      "Trong tim em có chỗ nào cho anh không?.",
      "Vận tốc trái tim nhanh không em nhỉ?\nĐể anh tính quãng đường đi đến trái tim em..",
      "Ngoài kia đám cưới linh đình.\nBao giờ thì đến lượt mình em ơi.",
      "Tay anh đây ấm lắm,\nem muốn nắm thử không?.",
      "1, 2, 3, 5 em có đánh rơi nhịp nào không?.",
      "Em xinh đẹp ơi,\nlàm con dâu mẹ anh không?.",
      "Cần lắm một em gái mưa!.",
      "Giá có em người yêu để cùng khám phá thế giới.",
      "Mình cũng đẹp trai,\nsao chả ai để ý?.",
      "Đông về tay anh lạnh lắm,\nnhưng anh vẫn sẵn lòng sưởi ấm tay em.",
      "Mọi người đều yêu cái đẹp,\nnên anh yêu em.",
      "Bão to, cây đổ.\nSao em chưa đổ anh?.",
      "Bố em có phải là một thợ kim hoàn không?\nSao em giống viên kim cương vậy?.",
      "Với thế giới thì em chỉ là một người.\nCòn với anh, em là cả thế giới.",
      "Bố em có phải là tên trộm không?\nSao có thể trộm vì sao và gắn vào mắt em như thế?.",
      "Anh như thế này,\nđã đủ tiêu chuẩn làm bạn trai em chưa?.",
      "Em có muốn làm Mặt Trời duy nhất của anh không?",
      "Này em ơi,\nmẹ anh đang gọi con dâu kìa.",
      "Giờ nếu có cô gái nào nguyện bên anh,\nanh sẽ khiến cô ấy hạnh phúc mãi về sau.",
      "Chỉ cần em yêu anh thôi,\ncòn cả thế giới cứ để anh lo.",
      "Cuộc đời này chắc chắn không như ý anh muốn,\nvậy em sẽ như ý anh muốn.",
      "Em có thể đưa anh đến tiệm bánh được không?\nVì anh cũng muốn có một chiếc bánh Cutie giống như em vậy.",
      "Chán thả thính rồi, ai cưa đi để anh đổ thử một lần.",
      "Anh cá với em rằng em là tay trộm chuyên nghiệp.\nBởi vì anh mới nhìn thấy em ở đây và trong nháy mắt là em đã đánh cắp trái tim của anh rồi.",
      "Ngày đó trời mưa lớn lắm,\nanh gặp được em,\nem không thấy anh,\nanh không thấy mưa.",
      "Nếu mỗi lần nhớ tới em anh được 500 đồng chắc giờ này anh đã vượt xa Bill Gates.",
      "Em có biết rằng anh nhớ em nhiều lắm không?\nAnh ăn không ngon nhưng ngủ như điên, anh đi giầy quên đi tất, ăn sáng quên đánh răng, anh dùng xăng vo gạo, anh khờ khạo cũng chỉ vì yêu em đó.",
      "Em ơi! Em là nghề gì đấy….?\nSao đêm nào em cũng hiện lên trong giấc mơ của anh vậy?\nAnh chẳng biết làm thế nào nữa cả.\nLàm người yêu anh em nhé!.",
      "Em ơi ! Khi em đọc tin nhắn này, em nợ anh cuộc hẹn.\nXóa tin nhắn này, em nợ anh cuộc tình.\nLưu tin là em nợ anh 1 nụ hôn.\nTrả lời anh, em nợ anh tất cả.\nCòn nếu em không trả lời thì em đã yêu anh !!! hihi.",
      "Ðiều duy nhất đôi mắt em chưa nói cho anh biết là tên của em.",
      "Anh thà được một lần ngửi được mùi tóc thơm của em.\nAnh thà được mộ lần xiết chặt bàn tay của em, anh thà được một lần nếm hương vị ngọt từ nụ hôn của em còn hơn là sống bất tử mà không được điều ấy.",
      "Chứng nghiện thức đêm cùng nỗi nhớ em,\nanh đã cố nhưng sửa không được.",
      "Anh muốn gửi tin nhắn này đến em hôm nay vì hôm nay anh cảm thấy yêu em nhiều đến bất thường.",
      "Ô tô thì đã có chỗ đỗ. Còn em thì đã đỗ trong tim anh!",
"Câu thả thính là anh copy đó, nhưng tình cảm dành cho em là thật lòng.",
"Gần mực thì đen. Gần em anh cảm thấy rất hạnh phúc!",
"Em có thể cười một chút không? Ly cafe của anh quên cho đường rồi.",
"Thay vì tặng em một đóa hoa hồng không héo, hãy để anh gửi em một mối tình không phai.",
"Hỏi em đi đứng thế nào. Năm lần bảy lượt ngã vào tim anh!",
"Năm nay anh vẫn một mình, nếu em cũng vậy thì mình cùng yêu!",
"Mượn xe nhớ đổ đầy bình. Mượn tim nhớ đổ đầy tình giúp anh!",
"Anh đây chẳng thích nhiều lời. Nhìn em là biết cả đời của anh!",
"Da anh đen vì mải ngắm nụ cười tỏa nắng của em đó!",
"Đen Vâu thì muốn về quê trồng rau, nuôi cá. Còn anh thì muốn về hỏi ba má cưới em.",
"Anh tuy học Lý rất giỏi, nhưng lại chẳng thể tính được tần số tim đập khi gặp em.",
"Nếu sốt cao quá thì gọi cấp cứu. Nếu nhớ anh quá thì chờ xíu anh qua.",
"Sáng anh nhớ tôi thì tối anh nhớ sang",
"Bình minh là ở phía Đông, còn bình yên là ở phía anh đây nè.",
"Tiêu chuẩn người yêu của anh là “như em” đó.",
"Công An hỏi Anh mua ma túy ở đâu, anh liền kể về lần đầu tiên trông thấy nụ cười của em.",
"1,2,3 con thỏ. Cho tớ hỏi nhỏ là cậu đã có người yêu chưa",
"Anh vẽ bầu trời xanh. Em tô hoa hồng đỏ. Lại đây em nói nhỏ. Em cực kỳ thích anh.",
"Hoa hồng thì màu đỏ. Violet màu xanh. Hôm nào em cũng sốt. Vì em bận yêu anh.",
"Chúng ta có 1 điểm chung. Đó chính là cùng yêu bản thân anh.",
"Anh biết cài Win chứ? Cài giúp em hệ điều hành nào mà có giao diện là anh nha!",
"Không mơ cổ tích hoang đường. Chỉ mơ giấc mộng đời thường có anh.",
"Đường em đi toàn hoa với cỏ. Biết lấy gì bày tỏ với anh đây?",
"Thương anh chẳng biết ngày mai. Thương anh chẳng biết mình sai chỗ nào.",
"Trời mưa bong bóng phập phồng. Má em đã giục lấy chồng rồi anh!",
"Tính em vốn dĩ thật thà. Yêu anh em phải nói ra thành lời.",
"Gọi cậu là bút cũ bởi vì tớ luôn yêu cậu hết mực.",
"Ba đồng một mớ trầu cau. Anh cho em hỏi cưới nhau ngày nào?",
"Hôm nay trời đổ cơn mưa. Anh muốn tự đổ hay để em cưa?",
"Dăm ba chén rượu ly trà. Thứ em say nhất chỉ là anh thôi.",
"Gọi em là dân thường bởi vì gặp em anh sẽ thương dần.",
"Gọi anh là chim sẻ, vì anh ăn sâu ở trong tâm trí em.",
"Cho em liều thuốc an thần. Để tim ổn định khi gần bên anh.",
"Bao nhiêu năm em học Địa lý mà vẫn chưa thể nào tìm được vị trí của anh.",
"Bao nhiêu cân thính cho vừa, bao nhiêu cân bả mới lừa được anh.",
"Tính em chẳng thích lưng chừng. Yêu em chẳng sợ cắm sừng đâu anh.",
"Ngắm mây ngắm cả bầu trời. Yêu em yêu mãi trọn đời nhé anh.",
"Chén kia là để uống trà. Lồng đèn để ngắm. Em là để yêu.",
"Em vốn chỉ yêu bản thân mình. Nhưng giờ lại muốn ngoại tình với anh.",
"10 năm cắn kẹo cũng chẳng thể bằng một tẹo hun anh.",
"Nếu sốt cao thì hãy gọi xe cấp cứu. Còn nhớ em nhiều thì chờ một xíu em sang.",
"Anh ơi nước biển màu xanh. Thời gian màu tím. Tim anh màu gì?",
"Đêm rằm có bánh Trung thu. Tiện cho em hỏi gu anh là gì?",
"Em hôm nay vừa hâm vừa dở. Anh bước vào che chở có được không?",
"Con cóc là cậu ông trời. Còn anh là cả cuộc đời của em.",
"Chắt chiu từ những ngày xưa - Mẹ sinh em để bây giờ cho anh.",
"Hôm nay em học Toán hình. Tròn vuông chẳng có toàn hình bóng anh.",
"Họ thích nghe nhạc vì lời. Còn em lại thích trọn đời có anh.",
"Anh ơi trăng khuyết lại tròn. Dẫu trời có sập vẫn còn có em.",
"Em ăn cơm chưa ?",
"Anh thích kitkat hay là kiss em?",
"Người ta mê mẩn bóng cười. Còn em mê mẩn bóng người em thương.",
"Muốn cho thiên hạ trầm trồ. Sao anh không thử làm bồ của em?",
"Mẹ sinh em không phải để em vất vả, mà sau này để gả cho anh.",
"Chiều Tây Hồ dập dềnh sóng vỗ. Em chỉ cần bến đỗ là anh.",
"Mong anh tốt nghiệp 2 bằng. Một bằng đại học, một bằng lòng em.",
"Lời của anh toàn những đường với mật. Nhưng chết thật em lại là con ong.",
"Em thích uống trà chanh. Thích ăn luôn cả bánh. Vì trong Chanh và Bánh. Đều có một chút Anh.",
"Mặt tròn như cái quạt mo. Anh nào yêu được ấm no cả đời.",
"Tết ngồi cắn chút hạt dưa. Bao lâu mới được anh đưa về nhà?",
"Mượn xe nhớ đổ đầy bình. Mượn tim nhớ đổ đầy tình giúp em.",
"Thính đâu để có nhiều thêm. Tình đâu mà mãi dịu êm hả người?",
"Anh ơi mai mốt mình già. Về quê nuôi cá, thả gà không anh?",
"Nước non phong cảnh hữu tình. Liệu anh có muốn chúng mình nên duyên?",
"Trời buồn trời đổ mưa ngâu. Mẹ anh đã có con dâu chưa nè?",
"Lưu số em đi, khi nào má có cần con dâu thì gọi cho em.",
"Thương nhau mấy núi cũng trèo. Anh chưa có gấu thì theo em về!",
"Mẹ mua cho em heo đất. Tiền em đem cất sau này cưới anh.",
"Bình yên là một bờ vai. Mình đem ra đổi bằng 2 nụ cười.",
"Chỗ em thì không nắng. Chả biết chỗ nào mưa. Giờ em để ý mỗi. Anh đã yêu em chưa?",
"Em đăng story không phải để thả thính, mà cái chính là để anh xem.",
"Hôm nay em đói cồn cào. Ship em một chút ngọt ngào đi anh.",
"Mọi người bảo em là nít ranh. Nhưng thật ra em lại Need anh.",
"Dạo này an ninh tốt thật đấy. Mãi chẳng thấy ai đánh cắp trái tim.",
"Trời mưa thì mặc trời mưa. Em mà không thích anh cưa đằng giời.",
"Anh không phải đồ tồi chứ? Vậy thì yêu em đừng từ chối!",
"Em độc thân, anh cũng độc thân. Chắc không phải ngẫu nhiên đâu nhỉ?",
"Tóc mai, sợi ngắn, sợi dài. Bỏ anh không được thương hoài mệt ghê.",
"Giữa dòng đời tấp nập. Em thấy anh mập nên em yêu.",
"Tình yêu con tằm ỉm trong tơ. Tình yêu của tớ ỉm trong tim.",
"Order giùm em một tình yêu chẳng phai. Giá phải chăng nhưng chắc chẳng phải anh?",
"Muốn chăm sóc anh đến già. Muốn là quần áo, muốn là vợ anh.",
"Tim em đã bật đèn xanh. Mà sao anh mãi đạp phanh thế này?",
"Cây đa giếng nước sân đình. Bao giờ em hết một mình đây anh?",
"Nếu trái đất này không có trọng lực thì em vẫn cứ Đổ vì anh!",
"Em thích thứ lấp lánh. Thích cả matcha xanh. Quên không nói với anh. Cả anh em cũng thích.",
"Hoa không sương hoa vẫn cứ nở. Thương em rồi... trắc trở anh có thương?",
"Hoàng hôn thì màu tím. Nhưng em thích màu hồng. Tim em vẫn còn trống. Anh có muốn vào không?",
"Em thích anh là thật nhưng trước dấu phẩy là đùa còn sau dấu phẩy cũng thế.",
"Quyết không tiêu từ giờ đến Tết. Để dành tiền mua hết trái tim anh.",
"Anh biết sửa tivi không? Xem giúp em sao kênh nào cũng có bóng dáng của anh vậy?",
"Trăng lên đỉnh núi trăng tà. Anh yêu em thật hay là yêu chơi?",
"Mời cậu ăn bát phở lòng tái. Để rồi mong cậu phải lòng tớ.",
"Vũ trụ của người ta. Là màu đen huyền bí. Vũ trụ em bé tí. Thu nhỏ lại là anh.",
"Càng phân tích thì tim em càng nhức nhối. Mà sao anh nỡ trị tuyệt đối tình em. Em yêu anh bằng định lý chân thành. Và tình em đã tiến về vô cực.",
"Nắng nơi em nắng hoài không tắt. Yêu anh rồi, yêu mãi không thôi.",
"Trời không xanh. Mây cũng không trắng. Em không say nắng. Nhưng em lại say anh.",
"Đừng để em lỡ thời. Anh hãy mở lời nói yêu em!",
"La bàn chỉ hướng Bắc. Xong lại chỉ hướng Nam. Tớ chỉ hướng về cậu. Thứ khác tớ không ham.",
"Nhân gian vốn lắm bộn bề. Sao không bỏ hết rồi về bên em?",
"Chủ nhật sắp qua. Thứ 2 gần đến. Người em thương mến. Chỉ có anh thôi.",
"Nếu anh thích người thú vị thì em đây chính là một ví dụ.",
"Hôm nay em đi học. Bị điểm kém môn Anh. Cô dạy Yêu là Love. Mà em viết tên anh.",
    "Muốn ăn gạo thì phải trồng lúa. Muốn có công chúa thì phải yêu em.",
    "Cậu giống hệt Google vậy đó bởi cậu có tất cả những gì tớ muốn tìm kiếm.",
    "Có tòa lâu đài nhỏ. Ở trong đó có em. Anh nhìn mà xem xem. Cứu em nhanh đi chứ.",
    "Không muốn đen thì phải tránh nắng. Không muốn say nắng thì tránh em ra.",
   "Hoa cà màu tím... Hoa tulip màu xanh. Lẽ nào anh lại không biết? Có người thầm thích anh!",
    "Anh có thể ngắm lại hoàng hôn vào ngày mai nếu bỏ lỡ. Nhưng bỏ lỡ em rồi thì anh sẽ không gặp lại lần thứ 2 đâu.",
    "Thời tiết trái gió trở trời. Tim em lỡ nhịp cả đời thương anh.",
    "Em học Văn thì dốt. Tính toán cũng chẳng nhanh. Hỏi em học gì tốt? Đó là môn yêu Anh.",
    "Người ta say rượu với say tình... Em đây ngốc nghếch say mình anh thôi.",
    "Đêm Hà Nội sương mù bao phủ. Nhớ anh rồi có ngủ được đâu.",
    "Tài nấu ăn em hơi ẩu, chẳng biết nấu gì trừ món lẩu tình yêu.",
    "Bông hoa thì cần cái chậu. Còn tớ chỉ cần CẬU thôi!",
    "Hảo hảo làm em cay. Còn anh làm em say!",
    "Bắc Đẩu đã có Nam Tào. Còn anh đã có người nào hay chưa?",
    "Tim em đã bật đèn xanh. Yêu em thì nói nhanh nhanh lên nào.",
    "Giới hạn của hàm số là lim, còn giới hạn của trái tim tớ chính là cậu.",
    "Thức khuya quá thì hay dễ đói. Thay vì chọn mỳ gói, chi bằng chọn ăn em.",
    "Đêm nay trăng sáng lờ mờ. Giường anh có rộng, em nhờ một đêm.",
    "Em không biết xào ke đập đá. Em chỉ biết may vá và chăm con.",
    "Đừng nghĩ em xấu mà chê. Yêu em thì biết nó phê cỡ nào.",
    "Thịt không bảo quản thì thịt thiu. Anh mà không quản họ iu em giờ.",
    "Em là con nhà gia giáo. Chỉ cần anh huýt sáo là lên phường.",
    "Lửa gần rơm lâu ngày cũng bén. Thích lâu rồi cho chén được không anh?",
    "Nấu ăn là việc anh làm. Còn ăn anh là việc của em.",
    "Good girl thì muốn tặng vòng tay. Còn em thì muốn anh còng tay.",
    "Nếu anh thấy tương lai mù mịt. Nhắm mắt vào để em thịt anh nha.",
    "Gọi anh là sự thật vì em chỉ muốn vạch trần.",
    "Lời nói chẳng mất tiền mua, dại gì không nói để lừa được anh.",
    "Dăm ba cây kẹo mút làm sao cuốn hút bằng anh.",
    "Trưởng thành thật lắm chông gai. Tối nay biết ngủ cùng ai bây giờ?",
    "Ngồi chờ anh tới. Anh không tới em chờ anh mới.",
    "Em không phải quảng cáo. Nên anh đừng bỏ qua.",
    "Bad girl không tốt. Good girl không vui. Em vui hay tốt, điều đó hên xui.",
    "Thức tới sáng vì quá chán. Ngủ muộn màng vì nhớ chàng.",
    "Trai thì không thiếu nhưng chủ yếu em cần mỗi anh.",
    "Vì mật mà ong thật liều. Vì anh mà em... yêu thật lòng.",
    "Anh thử dữ với em xem. Thu coi em co du anh khong.",
    "Thay vì bế tắc sao anh không thử be em.",
    "Nếu có 2 chồng sách, một to và một nhỏ thì tớ sẽ là chồng nhỏ còn cau se la chong to.",
    "Em có 2 cái kẹo, anh có 1 cái kẹo vậy em hon anh 1 cai nha.",
    "Hiphop never die. Muốn lái chị không hả em trai?",
    "Too dark thì cần ánh sáng. To night thì cần anh sang.",
    "Nếu anh rep inbox thì tối nay anh rock in bed.",
    "Em là Bad girl. Nhưng chắc chắn không phải là Bad choice",
    "Trong game trường em đánh gục tất cả. Dưới tình trường em gục ngã trước anh",
    "Anh say là do ai? Chắc chắn là “your eyes”",
    "Em mặc gì cũng được, nhưng đừng mặc kệ anh",
    "Từ khi yêu em anh đã bỏ game. Vì em là tất cả những gì anh muốn chơi",
    "Tán em bằng hai câu. Anh thích đi Lai Châu",
    "Thân em như hoa trên cành. Hoa thì dễ rụng còn em thì dễ thương",
    "Covid thì em không dính, nhưng chắc chắn thích anh thì em đã dương tính.",
    "Gọi em là bánh mì bơ sữa. Bởi vì em vừa đặc biệt mà lại thơm ngon",
    "Anh là mây, em là gió. Đứa nào xen vào là con 🐶.",
    "Ông trời cho tôi gương mặt xinh xắn, đáng yêu. Nhưng ông trời lại lấy đi người công nhận đó.",
    "Liệu chân tình có đổi được chân gà?",
    "Em không phải thiếu nữ, em thiếu tiền.",
    "Người ta buồn vì mối tình dang dở, còn tôi buồn vì bát phở hơi vơi :)))",
    "Chuyện tình cảm không nên đùa giỡn, vì đùa giỡn sẽ rất mắc cười.",
    "Người ta ôm mộng giàu sang, còn em ôm mộng y chang nhiều người.",
    "Cắm sừng ai thì cắm chứ đừng cắm cơm quên bật nút.",
    "Thời tiết này làm gì cũng thích, nhưng thích nhất là không làm gì.",
    "Gọi em là pháp sư, vì em biết mọi thứ trừ yêu.",
    "So với việc say đắm một ai đó, tôi nghĩ mình hợp với say xỉn hơn.",
    "Người đẹp thường nói nửa vời là bởi vì...",
    "Yêu em đi em cho hôn má. Nếu mà yêu quá thì mình hôn môi",
    "Gọi em là gió, vì gặp em là anh trúng. ",
    "Gọi em là dân thường, vì gặp em anh sẽ thương dần.",
    "Bad Girl chỉ muốn tha anh tới giường. Còn em thì cũng vậy",
    "Anh ăn cơm chưa?",
    "Gọi em là phép tu từ, vì em gợi hình, gợi cảm.",
    "Lung linh trong chút nắng chiều. Yêu anh say đắm, muốn liều Kết Hôn",
    "Thích em, anh cứ tỏ tình. Được thì ăn cả, ngã thì unfriend",
    "Xuân sang cây lá có cành. Vậy cho em hỏi anh đã có ai",
    "30 mình đón giao thừa. Ra giêng mình cưới, là vừa nha anh",
    "New year nhưng mà em chỉ thích Near you",
    "Tết nay đã có hoa đào. Còn em chưa có anh nào đón đưa",
    "Gọi anh là Titanic, vì mỗi khi thấy anh là em chìm đắm"
];
const nam = [
    { timer: '00:00:00', message: ['{thinh}'] },
    { timer: '00:30:00', message: ['{thinh}'] },
    { timer: '05:00:00', message: ['\n{thoitiet}'] },
    { timer: '06:00:00', message: ['{thinh}'] },
    { timer: '07:00:00', message: ['{thinh}'] },
    { timer: '08:00:00', message: ['{thinh}'] },
    { timer: '09:00:00', message: ['{thinh}'] },
    { timer: '10:00:00', message: ['{thinh}'] },
    { timer: '11:00:00', message: ['{thinh}'] },
    { timer: '12:00:00', message: ['{thinh}'] },
    { timer: '12:30:00', message: ['{thinh}'] },
    { timer: '13:00:00', message: ['{thinh}'] },
    { timer: '14:00:00', message: ['{thinh}'] },
    { timer: '15:00:00', message: ['{thinh}'] },
    { timer: '16:00:00', message: ['{thinh}'] },
    { timer: '17:00:00', message: ['{thinh}'] },
    { timer: '18:00:00', message: ['{thinh}'] },
    { timer: '19:00:00', message: ['{thinh}'] },
    { timer: '20:00:00', message: ['{thinh}'] },
    { timer: '21:00:00', message: ['{thinh}'] },
    { timer: '22:00:00', message: ['{thinh}'] },
    { timer: '23:00:00', message: ['{thinh}'] }
  ];

module.exports.onLoad = o => setInterval(async () => {
 const r = a => a[Math.floor(Math.random() * a.length)];
 const currentTime = moment().tz('Asia/Ho_Chi_Minh').format('HH:mm:ss');

 if (á = nam.find(i => i.timer === currentTime)) {
 const gio = moment().tz('Asia/Ho_Chi_Minh').format('HH:mm:ss || DD/MM/YYYY');

var msg = r(á.message);
var tinh = [
"Bắc Ninh", "Hồ Chí Minh", "Đà Nẵng", "Hải Phòng", "Cần Thơ", "Hải Dương", "Hà Nội",
"Quảng Ninh", "Thái Bình", "Nam Định", "Ninh Bình", "Thái Nguyên", "Phú Thọ", "Vĩnh Phúc",
"Bắc Giang", "Lạng Sơn", "Quảng Bình", "Quảng Trị", "Thừa Thiên Huế", "Quảng Nam", "Quảng Ngãi",
"Bình Định", "Phú Yên", "Khánh Hòa", "Ninh Thuận", "Bình Thuận", "Kon Tum", "Gia Lai", "Đắk Lắk",
"Đắk Nông", "Lâm Đồng", "Bình Phước", "Tây Ninh", "Bình Dương", "Đồng Nai", "Long An", "Đồng Tháp",
"Tiền Giang", "An Giang", "Bà Rịa - Vũng Tàu", "Bến Tre", "Bạc Liêu", "Cà Mau", "Hậu Giang",
"Kiên Giang", "Sóc Trăng", "Trà Vinh", "Vĩnh Long", "Thanh Hóa"
];
const city = tinh[Math.floor(Math.random() * tinh.length)];
 const result = await findWeather(city);
 var currentDay = result[0].current.day.replace(/Friday/g, "Thứ 6").replace(/Saturday/g, "Thứ 7").replace(/Sunday/g, "Chủ nhật").replace(/Monday/g, "Thứ 2").replace(/Tuesday/g, "Thứ 3").replace(/Wednesday/g, "Thứ 4").replace(/Thursday/g, "Thứ 5");
 var date = result[0].current.date;
 var dateFormat = `Ngày ${date.split("-")[2]}-${date.split("-")[1]}-${date.split("-")[0]}`;
 var skytext = result[0].current.skytext.toString()
 "Cloudy" == skytext ? skytext = "Mây" : "Sunny" == skytext ? skytext = "Nắng" : "Partly Cloudy" == skytext ? skytext = "Mây một phần" : "Mostly Cloudy" == skytext ? skytext = "Mây rất nhiều" : "Rain" == skytext ? skytext = "Mưa" : "Thunderstorm" == skytext ? skytext = "Bão" : "Snow" == skytext ? skytext = "Tuyết" : "Fog" == skytext || "Haze" == skytext ? skytext = "Sương mù" : "Clear" == skytext ? skytext = "Trời trong" : "Light Rain" == skytext ? skytext = "Mưa nhẹ" : "Mostly Clear" == skytext && (skytext = "Trời trong rất nhiều");
 var winddisplay = result[0].current.winddisplay.toString().split(" ")[2];
 "Northeast" == winddisplay && (winddisplay = "Hướng Đông Bắc"), "Northwest" == winddisplay && (winddisplay = "Hướng Tây Bắc"), "Southeast" == winddisplay && (winddisplay = "Hướng Đông Nam"), "Southwest" == winddisplay && (winddisplay = "Hướng Tây Nam"), "East" == winddisplay && (winddisplay = "Hướng Đông"), "West" == winddisplay && (winddisplay = "Hướng Tây"), "North" == winddisplay && (winddisplay = "Hướng Bắc"), "South" == winddisplay && (winddisplay = "Hướng Nam");
 var thoitiet = `[  ${gio}  ]\n──────────────────\n[🗺️] →⁠ Cập nhật thời tiết tại: ${result[0].location.name}\n[🌡] →⁠ Nhiệt độ: ${result[0].current.temperature}°${result[0].location.degreetype}\n[✏️] →⁠ Mô tả: ${skytext}\n[♒] →⁠ Độ ẩm: ${result[0].current.humidity}%\n[💨] →⁠ Hướng gió: ${result[0].current.windspeed} ${winddisplay}\n[⏰] →⁠ Ghi nhận vào: ${result[0].current.observationtime}\n[🗺️] →⁠ Từ trạm ${result[0].current.observationpoint}\n[☁] → Dùng lệnh nasa + tỉnh/tp để xem thời tiết trong 3 ngày tới.\n──────────────────\n🔄 Đây Là Tin Nhắn Tự Động`;
 
 msg = msg.replace(/{thoitiet}/, thoitiet);

 msg = {
 body: msg,
 };

 global.data.allThreadID.forEach(i => o.api.sendMessage(msg, i));
 }
}, 1000);

module.exports.run = () => {};